nodeLinker: node-modules

npmRegistryServer: "http://localhost:5000"

npmScopes:
  react-examples:
    npmAlwaysAuth: true
    npmAuthToken: "\"T6BO56J0CMqk9zrIqR7gDQ==\""
    npmPublishRegistry: "http://localhost:5000"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

unsafeHttpWhitelist:
  - localhost

yarnPath: .yarn/releases/yarn-3.0.1.cjs
